#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun May 04 10:55:18 CEST 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim design_2_wrapper_behav -key {Behavioral:sim_1:Functional:design_2_wrapper} -tclbatch design_2_wrapper.tcl -protoinst "protoinst_files/design_2.protoinst" -view /home/pcoli/Project_Folder/Xilinx_Vivado/MotorDriver/speedsensorbehavior.wcfg -log simulate.log"
xsim design_2_wrapper_behav -key {Behavioral:sim_1:Functional:design_2_wrapper} -tclbatch design_2_wrapper.tcl -protoinst "protoinst_files/design_2.protoinst" -view /home/pcoli/Project_Folder/Xilinx_Vivado/MotorDriver/speedsensorbehavior.wcfg -log simulate.log

