# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/synth_1.xdc

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_SOC_MOTOR_DRIVER_0_0/design_2_SOC_MOTOR_DRIVER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_SOC_MOTOR_DRIVER_0_0 || ORIG_REF_NAME==design_2_SOC_MOTOR_DRIVER_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0_axi_periph_0/design_2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_100M_0/design_2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/oliwi/Documents/SOC/motor_driver_project/motor_driver_project.gen/sources_1/bd/design_2/design_2_ooc.xdc
